Repository aprilNeufeld/Portfolio, pull requests merged in 2022-07, with the labels that each got.

#11 Issue 13 - Fix hooks errors
  next-env.d.ts
  package-lock.json
  package.json
  src/lib/sanity.ts
  src/pages/post/[slug].tsx
  tsconfig.json
Labels: bug

#14 ISSUE-12-format-with-prettier
  .eslintrc.json
  .husky/pre-commit
  .prettierignore
  .prettierrc
  .vs/slnx.sqlite
  @types/block-content-to-react.d.ts
  next.config.js
  package-lock.json
  package.json
  src/components/BlockRenderer.tsx
  src/components/BlogPostCard.tsx
  src/components/DividerWithSpacing.tsx
  src/components/ElevationScroll.tsx
  src/components/FadingCardExpandable.tsx
  src/components/FancyChild.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/HeaderContent.tsx
  src/components/HorizontalExpandButton.tsx
  src/components/Layout.tsx
  src/components/ListItemSkeleton.tsx
  src/components/PageTitle.tsx
  src/components/Project.tsx
  src/custom.css
  src/lib/sanity.ts
  src/lib/staticFetching.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/preview.ts
  src/pages/blog.tsx
  src/pages/index.tsx
  src/pages/post/[slug].tsx
  src/pages/projects.tsx
  src/shared/types.ts
  src/store/blogSlice.tsx
  src/store/configureStore.ts
  src/store/index.ts
  src/store/projectsSlice.tsx
  src/store/userSlice.tsx
  src/styles.ts
  studio/sanity.json
  studio/schemas/author.js
  studio/schemas/blockContent.js
  studio/schemas/category.js
  studio/schemas/post.js
  studio/schemas/schema.js
  studio/src/deskStructure.js
  studio/src/previews/IframePreview.css
  studio/src/previews/PostPreview.js
  tsconfig.json
  vercel.json
Labels: maintenance

#18 ISSUE-17-move-to-aprilneufeld-domain
  .prettierignore
  LICENSE.txt
  README.md
  package.json
  src/components/Footer.tsx
  src/components/HeaderContent.tsx
  src/lib/staticFetching.tsx
  src/pages/post/[slug].tsx
  src/store/projectsSlice.tsx
  src/store/userSlice.tsx
  studio/package.json
Labels: enhancement

#22 ISSUE-5-migrate-to-mui
  package-lock.json
  package.json
  src/components/BlogPostCard.tsx
  src/components/DividerWithSpacing.tsx
  src/components/ElevationScroll.tsx
  src/components/FadingCardExpandable.tsx
  src/components/FancyChild.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/HeaderContent.tsx
  src/components/HorizontalExpandButton.tsx
  src/components/Layout.tsx
  src/components/ListItemSkeleton.tsx
  src/components/PageTitle.tsx
  src/components/Project.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/blog.tsx
  src/pages/index.tsx
  src/pages/post/[slug].tsx
  src/pages/projects.tsx
  src/store/configureStore.ts
  src/styles.ts
Labels: enhancement

#25 ISSUE-20-fix-link-colour-and-behaviour
  src/components/ContactLinks.tsx
  src/components/ExternalLink.tsx
  src/components/Footer.tsx
  src/components/HeaderContent.tsx
Labels: enhancement

#27 ISSUE-26-align-link-styles
  package-lock.json
  package.json
  src/components/BlogPostCard.tsx
  src/components/ContactLinks.tsx
  src/components/ExternalLink.tsx
  src/components/Footer.tsx
  src/components/Layout.tsx
  src/components/ProjectItem.tsx
  src/components/StyledLink.tsx
  src/components/StyledLinkify.tsx
  src/lib/customMatchDecorator.ts
  src/pages/index.tsx
  src/pages/post/[slug].tsx
  src/pages/projects.tsx
  src/styles.ts
Labels: bug, maintenance

#29 ISSUE-28-fix-huge-icon-flash
  package-lock.json
  package.json
  src/lib/createEmotionCache.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
Labels: bug
